/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary) / 0.05)',
          100: 'rgb(var(--color-primary) / 0.1)',
          200: 'rgb(var(--color-primary) / 0.2)',
          300: 'rgb(var(--color-primary) / 0.3)',
          400: 'rgb(var(--color-primary) / 0.4)',
          500: 'rgb(var(--color-primary) / 0.5)',
          600: 'rgb(var(--color-primary) / 0.6)',
          700: 'rgb(var(--color-primary) / 0.7)',
          800: 'rgb(var(--color-primary) / 0.8)',
          900: 'rgb(var(--color-primary) / 0.9)',
          950: 'rgb(var(--color-primary) / 0.95)',
        },
        'primary-light': {
          500: 'rgb(var(--color-primary-light) / 0.5)',
          600: 'rgb(var(--color-primary-light) / 0.6)',
          700: 'rgb(var(--color-primary-light) / 0.7)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary) / 0.05)',
          100: 'rgb(var(--color-secondary) / 0.1)',
          200: 'rgb(var(--color-secondary) / 0.2)',
          300: 'rgb(var(--color-secondary) / 0.3)',
          400: 'rgb(var(--color-secondary) / 0.4)',
          500: 'rgb(var(--color-secondary) / 0.5)',
          600: 'rgb(var(--color-secondary) / 0.6)',
          700: 'rgb(var(--color-secondary) / 0.7)',
          800: 'rgb(var(--color-secondary) / 0.8)',
          900: 'rgb(var(--color-secondary) / 0.9)',
        },
        accent: {
          50: 'rgb(var(--color-accent) / 0.05)',
          100: 'rgb(var(--color-accent) / 0.1)',
          200: 'rgb(var(--color-accent) / 0.2)',
          300: 'rgb(var(--color-accent) / 0.3)',
          400: 'rgb(var(--color-accent) / 0.4)',
          500: 'rgb(var(--color-accent) / 0.5)',
          600: 'rgb(var(--color-accent) / 0.6)',
          700: 'rgb(var(--color-accent) / 0.7)',
          800: 'rgb(var(--color-accent) / 0.8)',
          900: 'rgb(var(--color-accent) / 0.9)',
        },
        success: {
          100: 'rgb(var(--color-success) / 0.1)',
          200: 'rgb(var(--color-success) / 0.2)',
          500: 'rgb(var(--color-success) / 0.5)',
          800: 'rgb(var(--color-success) / 0.8)',
        },
        warning: {
          100: 'rgb(var(--color-warning) / 0.1)',
          200: 'rgb(var(--color-warning) / 0.2)',
          500: 'rgb(var(--color-warning) / 0.5)',
          800: 'rgb(var(--color-warning) / 0.8)',
        },
        error: {
          100: 'rgb(var(--color-error) / 0.1)',
          200: 'rgb(var(--color-error) / 0.2)',
          500: 'rgb(var(--color-error) / 0.5)',
          800: 'rgb(var(--color-error) / 0.8)',
        },
        gray: {
          50: 'rgb(var(--color-gray-50) / 1)',
          100: 'rgb(var(--color-gray-100) / 1)',
          200: 'rgb(var(--color-gray-200) / 1)',
          300: 'rgb(var(--color-gray-300) / 1)',
          400: 'rgb(var(--color-gray-400) / 1)',
          500: 'rgb(var(--color-gray-500) / 1)',
          600: 'rgb(var(--color-gray-600) / 1)',
          700: 'rgb(var(--color-gray-700) / 1)',
          800: 'rgb(var(--color-gray-800) / 1)',
          900: 'rgb(var(--color-gray-900) / 1)',
          950: 'rgb(var(--color-gray-950) / 1)',
        },
      },
      fontFamily: {
        sans: ['Inter var', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-in': 'slideInRight 0.3s ease-out',
      },
    },
  },
  plugins: [],
};